from fastapi import Request, HTTPException

from aiogram.utils.web_app import WebAppInitData, safe_parse_webapp_init_data
from config_reader import config

from db import User


def auth(request: Request) -> WebAppInitData:
    try:
        auth_string = request.headers.get("initData", None)
        if auth_string:
            data = safe_parse_webapp_init_data(
                config.BOT_TOKEN.get_secret_value(), auth_string
            )
            return data
        raise HTTPException(401, {"error": "Unauthorized"})
    except Exception as exc:
        raise HTTPException(401, {"error": "Unauthorized"}) from exc


async def check_user(user_id: int) -> User:
    user = await User.filter(id=user_id).first()
    if not user:
        raise HTTPException(401, {"error": "Unauthorized"})
    return user


def calculate_multiplier(gamemode: str, tags: list[str]) -> float:
    multiplier = 1.0

    if gamemode == "CHOOSE":
        multiplier *= 0.7
    elif gamemode == "ENTER":
        multiplier *= 1.2

    if not tags or "ALL" in tags:
        multiplier *= 1.0
    elif "UN" in tags and len(tags) == 1:
        multiplier *= 0.6
    elif "RARE" in tags:
        multiplier *= 1.3

    return round(multiplier, 2)


answer_map = {
    "colombia": "Colombia",
    "колумбия": "Colombia",
    "turkey": "Turkey",
    "турция": "Turkey",
    "india": "India",
    "индия": "India",
    "afghanistan": "Afghanistan",
    "афганистан": "Afghanistan",
    "albania": "Albania",
    "албания": "Albania",
    "angola": "Angola",
    "ангола": "Angola",
    "antigua and barbuda": "Antigua and Barbuda",
    "антигуа и барбуда": "Antigua and Barbuda",
    "argentina": "Argentina",
    "аргентина": "Argentina",
    "armenia": "Armenia",
    "армения": "Armenia",
    "aruba": "Aruba",
    "аруба": "Aruba",
    "austria": "Austria",
    "австрия": "Austria",
    "azerbaijan": "Azerbaijan",
    "азербайджан": "Azerbaijan",
    "bahamas": "Bahamas",
    "багамские острова": "Bahamas",
    "barbados": "Barbados",
    "барбадос": "Barbados",
    "belarus": "Belarus",
    "беларусь": "Belarus",
    "belgium": "Belgium",
    "бельгия": "Belgium",
    "belize": "Belize",
    "белиз": "Belize",
    "benin": "Benin",
    "бенин": "Benin",
    "bolivia": "Bolivia",
    "боливия": "Bolivia",
    "bosnia and herzegovina": "Bosnia and Herzegovina",
    "босния и герцеговина": "Bosnia and Herzegovina",
    "botswana": "Botswana",
    "ботсвана": "Botswana",
    "brunei": "Brunei",
    "бруней": "Brunei",
    "burundi": "Burundi",
    "бурунди": "Burundi",
    "cabo verde": "Cabo Verde",
    "кабо верде": "Cabo Verde",
    "cambodia": "Cambodia",
    "камбоджа": "Cambodia",
    "cameroon": "Cameroon",
    "камерун": "Cameroon",
    "canada": "Canada",
    "канада": "Canada",
    "central african republic": "Central African Republic",
    "центральная африканская республика": "Central African Republic",
    "bangladesh": "Bangladesh",
    "бангладеш": "Bangladesh",
    "algeria": "Algeria",
    "алжир": "Algeria",
    "andorra": "Andorra",
    "андорра": "Andorra",
    "australia": "Australia",
    "австралия": "Australia",
    "brazil": "Brazil",
    "бразилия": "Brazil",
    "bahrain": "Bahrain",
    "бахрейн": "Bahrain",
    "bhutan": "Bhutan",
    "бутан": "Bhutan",
    "chad": "Chad",
    "чад": "Chad",
    "chile": "Chile",
    "чили": "Chile",
    "china": "China",
    "китай": "China",
    "comoros": "Comoros",
    "коморос": "Comoros",
    "congo": "Congo",
    "конго": "Congo",
    "congo (democratic republic)": "Democratic Republic of the Congo",
    "конго (демократическая республика)": "Democratic Republic of the Congo",
    "democratic republic of congo": "Democratic Republic of the Congo",
    "democratic republic of the congo": "Democratic Republic of the Congo",
    "демократическая республика конго": "Democratic Republic of the Congo",
    "costa rica": "Costa Rica",
    "коста-рика": "Costa Rica",
    "коста рика": "Costa Rica",
    "костарика": "Costa Rica",
    "cuba": "Cuba",
    "куба": "Cuba",
    "cyprus": "Cyprus",
    "кипр": "Cyprus",
    "djibouti": "Djibouti",
    "джибути": "Djibouti",
    "dominica": "Dominica",
    "доминика": "Dominica",
    "east timor": "East Timor",
    "восточный тимор": "East Timor",
    "ecuador": "Ecuador",
    "эквадор": "Ecuador",
    "egypt": "Egypt",
    "египет": "Egypt",
    "el salvador": "El Salvador",
    "сальвадор": "El Salvador",
    "equatorial guinea": "Equatorial Guinea",
    "экваториальная гвинея": "Equatorial Guinea",
    "eritrea": "Eritrea",
    "эритрея": "Eritrea",
    "estonia": "Estonia",
    "эстония": "Estonia",
    "eswatini": "Eswatini",
    "эсватини": "Eswatini",
    "ethiopia": "Ethiopia",
    "эфиопия": "Ethiopia",
    "fiji": "Fiji",
    "фиджи": "Fiji",
    "finland": "Finland",
    "финляндия": "Finland",
    "gabon": "Gabon",
    "габон": "Gabon",
    "gambia": "Gambia",
    "гамбия": "Gambia",
    "czech republic": "Czech Republic",
    "чешская республика": "Czech Republic",
    "dominican republic": "Dominican Republic",
    "доминиканская республика": "Dominican Republic",
    "germany": "Germany",
    "германия": "Germany",
    "ghana": "Ghana",
    "гана": "Ghana",
    "greece": "Greece",
    "греция": "Greece",
    "grenada": "Grenada",
    "гренада": "Grenada",
    "guinea": "Guinea",
    "гвинея": "Guinea",
    "guinea-bissau": "Guinea-Bissau",
    "гвинея-бисау": "Guinea-Bissau",
    "france": "France",
    "франция": "France",
    "guatemala": "Guatemala",
    "гватемала": "Guatemala",
    "croatia": "Croatia",
    "хорватия": "Croatia",
    "guyana": "Guyana",
    "гайана": "Guyana",
    "haiti": "Haiti",
    "гаити": "Haiti",
    "honduras": "Honduras",
    "гондурас": "Honduras",
    "hungary": "Hungary",
    "венгрия": "Hungary",
    "iceland": "Iceland",
    "исландия": "Iceland",
    "indonesia": "Indonesia",
    "индонезия": "Indonesia",
    "iraq": "Iraq",
    "ирак": "Iraq",
    "israel": "Israel",
    "израиль": "Israel",
    "italy": "Italy",
    "италия": "Italy",
    "jamaica": "Jamaica",
    "ямайка": "Jamaica",
    "japan": "Japan",
    "япония": "Japan",
    "jordan": "Jordan",
    "иордания": "Jordan",
    "kazakhstan": "Kazakhstan",
    "казахстан": "Kazakhstan",
    "kuwait": "Kuwait",
    "кувейт": "Kuwait",
    "kyrgyzstan": "Kyrgyzstan",
    "кыргизстан": "Kyrgyzstan",
    "laos": "Laos",
    "лаос": "Laos",
    "lebanon": "Lebanon",
    "ливан": "Lebanon",
    "lesotho": "Lesotho",
    "лесото": "Lesotho",
    "libya": "Libya",
    "ливия": "Libya",
    "liechtenstein": "Liechtenstein",
    "лихтенштейн": "Liechtenstein",
    "lithuania": "Lithuania",
    "литва": "Lithuania",
    "luxembourg": "Luxembourg",
    "люксембург": "Luxembourg",
    "madagascar": "Madagascar",
    "мадагаскар": "Madagascar",
    "malawi": "Malawi",
    "малави": "Malawi",
    "malaysia": "Malaysia",
    "малайзия": "Malaysia",
    "maldives": "Maldives",
    "мальдивы": "Maldives",
    "mali": "Mali",
    "мали": "Mali",
    "ireland": "Ireland",
    "ирландия": "Ireland",
    "kiribati": "Kiribati",
    "кирибати": "Kiribati",
    "iran": "Iran",
    "иран": "Iran",
    "marshall islands": "Marshall Islands",
    "маршалл острова": "Marshall Islands",
    "mauritania": "Mauritania",
    "мавритания": "Mauritania",
    "mauritius": "Mauritius",
    "маврикий": "Mauritius",
    "liberia": "Liberia",
    "либерия": "Liberia",
    "latvia": "Latvia",
    "латвия": "Latvia",
    "malta": "Malta",
    "мальта": "Malta",
    "mexico": "Mexico",
    "мексика": "Mexico",
    "micronesia": "Micronesia",
    "микронезия": "Micronesia",
    "moldova": "Moldova",
    "молдова": "Moldova",
    "monaco": "Monaco",
    "монако": "Monaco",
    "mongolia": "Mongolia",
    "монголия": "Mongolia",
    "montenegro": "Montenegro",
    "черногория": "Montenegro",
    "morocco": "Morocco",
    "марокко": "Morocco",
    "mozambique": "Mozambique",
    "мозамбик": "Mozambique",
    "myanmar": "Myanmar",
    "мьянма": "Myanmar",
    "namibia": "Namibia",
    "намибия": "Namibia",
    "nauru": "Nauru",
    "науру": "Nauru",
    "nepal": "Nepal",
    "непал": "Nepal",
    "new zealand": "New Zealand",
    "новая зеландия": "New Zealand",
    "nicaragua": "Nicaragua",
    "никарагуа": "Nicaragua",
    "niger": "Niger",
    "нигер": "Niger",
    "nigeria": "Nigeria",
    "нигерия": "Nigeria",
    "north korea": "North Korea",
    "северная корея": "North Korea",
    "norway": "Norway",
    "норвегия": "Norway",
    "oman": "Oman",
    "оман": "Oman",
    "pakistan": "Pakistan",
    "пакистан": "Pakistan",
    "palau": "Palau",
    "палау": "Palau",
    "panama": "Panama",
    "панама": "Panama",
    "paraguay": "Paraguay",
    "парагвай": "Paraguay",
    "peru": "Peru",
    "перу": "Peru",
    "philippines": "Philippines",
    "филиппины": "Philippines",
    "poland": "Poland",
    "польша": "Poland",
    "portugal": "Portugal",
    "португалия": "Portugal",
    "qatar": "Qatar",
    "катар": "Qatar",
    "romania": "Romania",
    "румыния": "Romania",
    "russia": "Russia",
    "россия": "Russia",
    "rwanda": "Rwanda",
    "руанда": "Rwanda",
    "saint kitts and nevis": "Saint Kitts and Nevis",
    "saint kitts": "Saint Kitts and Nevis",
    "nevis": "Saint Kitts and Nevis",
    "сент-китс и невис": "Saint Kitts and Nevis",
    "сент китс и невис": "Saint Kitts and Nevis",
    "сенткитс и невис": "Saint Kitts and Nevis",
    "сенткитс": "Saint Kitts and Nevis",
    "невис": "Saint Kitts and Nevis",
    "saint lucia": "Saint Lucia",
    "святая люсия": "Saint Lucia",
    "netherlands": "Netherlands",
    "нидерланды": "Netherlands",
    "north macedonia": "North Macedonia",
    "северная македония": "North Macedonia",
    "saint vincent and the grenadines": "Saint Vincent and the Grenadines",
    "сент-винсент и гренадины": "Saint Vincent and the Grenadines",
    "san marino": "San Marino",
    "сан-марино": "San Marino",
    "sao tome and principe": "Sao Tome and Principe",
    "sao tome и principe": "Sao Tome and Principe",
    "senegal": "Senegal",
    "сенегал": "Senegal",
    "serbia": "Serbia",
    "сербия": "Serbia",
    "seychelles": "Seychelles",
    "сейшельские острова": "Seychelles",
    "sierra leone": "Sierra Leone",
    "сьерра-леоне": "Sierra Leone",
    "singapore": "Singapore",
    "сингапур": "Singapore",
    "slovakia": "Slovakia",
    "словакия": "Slovakia",
    "slovenia": "Slovenia",
    "словения": "Slovenia",
    "solomon islands": "Solomon Islands",
    "соломонские острова": "Solomon Islands",
    "south africa": "South Africa",
    "юар": "South Africa",
    "south korea": "South Korea",
    "южная корея": "South Korea",
    "south sudan": "South Sudan",
    "южный судан": "South Sudan",
    "taiwan": "Taiwan",
    "тайвань": "Taiwan",
    "tajikistan": "Tajikistan",
    "таджикистан": "Tajikistan",
    "tanzania": "Tanzania",
    "танзания": "Tanzania",
    "thailand": "Thailand",
    "таиланд": "Thailand",
    "togo": "Togo",
    "того": "Togo",
    "tonga": "Tonga",
    "тонга": "Tonga",
    "trinidad and tobago": "Trinidad and Tobago",
    "тринидад и тобаго": "Trinidad and Tobago",
    "tunisia": "Tunisia",
    "тунис": "Tunisia",
    "turkmenistan": "Turkmenistan",
    "туркменистан": "Turkmenistan",
    "tuvalu": "Tuvalu",
    "тувалу": "Tuvalu",
    "uganda": "Uganda",
    "уганда": "Uganda",
    "ukraine": "Ukraine",
    "украина": "Ukraine",
    "united arab emirates": "United Arab Emirates",
    "объединенные арабские эмираты": "United Arab Emirates",
    "united kingdom": "United Kingdom",
    "великобритания": "United Kingdom",
    "uruguay": "Uruguay",
    "уругвай": "Uruguay",
    "uzbekistan": "Uzbekistan",
    "узбекистан": "Uzbekistan",
    "vanuatu": "Vanuatu",
    "вануату": "Vanuatu",
    "saudi arabia": "Saudi Arabia",
    "саудовская аравия": "Saudi Arabia",
    "united states": "United States",
    "соединенные штаты": "United States",
    "somalia": "Somalia",
    "сомали": "Somalia",
    "vatican city": "Vatican City",
    "ватикан": "Vatican City",
    "venezuela": "Venezuela",
    "венесуэла": "Venezuela",
    "vietnam": "Vietnam",
    "вьетнам": "Vietnam",
    "yemen": "Yemen",
    "йемен": "Yemen",
    "zambia": "Zambia",
    "замбия": "Zambia",
    "zimbabwe": "Zimbabwe",
    "зимбабве": "Zimbabwe",
    "denmark": "Denmark",
    "дания": "Denmark",
    "burkina faso": "Burkina Faso",
    "буркина фасо": "Burkina Faso",
    "samoa": "Samoa",
    "самоа": "Samoa",
    "kenya": "Kenya",
    "кения": "Kenya",
    "bulgaria": "Bulgaria",
    "болгария": "Bulgaria",
    "georgia": "Georgia",
    "грузия": "Georgia",
    "papua new guinea": "Papua New Guinea",
    "папуа новая гвинея": "Papua New Guinea",
}
