from fastapi import Request, HTTPException

from aiogram.utils.web_app import WebAppInitData, safe_parse_webapp_init_data
from config_reader import config

from db import User


def auth(request: Request) -> WebAppInitData:
    try:
        auth_string = request.headers.get("initData", None)
        if auth_string:
            data = safe_parse_webapp_init_data(
                config.BOT_TOKEN.get_secret_value(), auth_string
            )
            return data
        raise HTTPException(401, {"error": "Unauthorized"})
    except Exception as exc:
        raise HTTPException(401, {"error": "Unauthorized"}) from exc


async def check_user(user_id: int) -> User:
    user = await User.filter(id=user_id).first()
    if not user:
        raise HTTPException(401, {"error": "Unauthorized"})
    return user


def calculate_multiplier(gamemode: str, tags: list[str]) -> float:
    multiplier = 1.0

    if gamemode == "CHOOSE":
        multiplier *= 0.7
    elif gamemode == "ENTER":
        multiplier *= 1.2

    if not tags or "ALL" in tags:
        multiplier *= 1.0
    elif "UN" in tags and len(tags) == 1:
        multiplier *= 0.6
    elif "RARE" in tags:
        multiplier *= 1.3

    return round(multiplier, 2)


answer_map = {
    "afghanistan": "Afghanistan",
    "афганистан": "Afghanistan",
    "albania": "Albania",
    "албания": "Albania",
    "algeria": "Algeria",
    "алжир": "Algeria",
    "andorra": "Andorra",
    "андорра": "Andorra",
    "angola": "Angola",
    "ангола": "Angola",
    "antigua and barbuda": "Antigua and Barbuda",
    "антигуа и барбуда": "Antigua and Barbuda",
    "argentina": "Argentina",
    "аргентина": "Argentina",
    "armenia": "Armenia",
    "армения": "Armenia",
    "australia": "Australia",
    "австралия": "Australia",
    "austria": "Austria",
    "австрия": "Austria",
    "azerbaijan": "Azerbaijan",
    "азербайджан": "Azerbaijan",
    "the bahamas": "The Bahamas",
    "багамы": "The Bahamas",
    "bahrain": "Bahrain",
    "бахрейн": "Bahrain",
    "adygea": "Adygea",
    "адыгея": "Adygea",
    "barbados": "Barbados",
    "барбадос": "Barbados",
    "belgium": "Belgium",
    "бельгия": "Belgium",
    "belize": "Belize",
    "белиз": "Belize",
    "benin": "Benin",
    "бенин": "Benin",
    "bhutan": "Bhutan",
    "бутан": "Bhutan",
    "bolivia": "Bolivia",
    "боливия": "Bolivia",
    "bosnia and herzegovina": "Bosnia and Herzegovina",
    "босния и герцеговина": "Bosnia and Herzegovina",
    "botswana": "Botswana",
    "ботсвана": "Botswana",
    "brazil": "Brazil",
    "бразилия": "Brazil",
    "brunei": "Brunei",
    "бруней": "Brunei",
    "bulgaria": "Bulgaria",
    "болгария": "Bulgaria",
    "burkina faso": "Burkina Faso",
    "буркина-фасо": "Burkina Faso",
    "burundi": "Burundi",
    "бурунди": "Burundi",
    "cambodia": "Cambodia",
    "камбоджа": "Cambodia",
    "cameroon": "Cameroon",
    "камерун": "Cameroon",
    "canada": "Canada",
    "канада": "Canada",
    "cape verde": "Cape Verde",
    "кабо-верде": "Cape Verde",
    "central african republic": "Central African Republic",
    "центральноафриканская республика": "Central African Republic",
    "цар": "Central African Republic",
    "центрально африканская республика": "Central African Republic",
    "chad": "Chad",
    "чад": "Chad",
    "chile": "Chile",
    "чили": "Chile",
    "china": "China",
    "кнр": "China",
    "colombia": "Colombia",
    "колумбия": "Colombia",
    "comoros": "Comoros",
    "коморские острова": "Comoros",
    "democratic republic of the congo": "Democratic Republic of the Congo",
    "демократическая республика конго": "Democratic Republic of the Congo",
    "belarus": "Belarus",
    "беларусь": "Belarus",
    "republic of the congo": "Republic of the Congo",
    "республика конго": "Republic of the Congo",
    "costa rica": "Costa Rica",
    "коста-рика": "Costa Rica",
    "cuba": "Cuba",
    "куба": "Cuba",
    "cyprus": "Cyprus",
    "кипр": "Cyprus",
    "czech republic": "Czech Republic",
    "чешская республика": "Czech Republic",
    "czechia": "Czech Republic",
    "чехия": "Chechnya",
    "denmark": "Denmark",
    "дания": "Denmark",
    "djibouti": "Djibouti",
    "джибути": "Djibouti",
    "dominica": "Dominica",
    "доминика": "Dominica",
    "altai republic": "Altai Republic",
    "республика алтай": "Altai Republic",
    "ecuador": "Ecuador",
    "эквадор": "Ecuador",
    "egypt": "Egypt",
    "египет": "Egypt",
    "el salvador": "El Salvador",
    "сальвадор": "El Salvador",
    "equatorial guinea": "Equatorial Guinea",
    "экваториальная гвинея": "Equatorial Guinea",
    "eritrea": "Eritrea",
    "эритрея": "Eritrea",
    "estonia": "Estonia",
    "эстония": "Estonia",
    "eswatini": "Eswatini",
    "эсватини": "Eswatini",
    "ethiopia": "Ethiopia",
    "эфиопия": "Ethiopia",
    "fiji": "Fiji",
    "фиджи": "Fiji",
    "finland": "Finland",
    "финляндия": "Finland",
    "france": "France",
    "франция": "France",
    "gabon": "Gabon",
    "габон": "Gabon",
    "the gambia": "The Gambia",
    "гамбия": "The Gambia",
    "georgia": "Georgia",
    "грузия": "Georgia",
    "germany": "Germany",
    "германия": "Germany",
    "ghana": "Ghana",
    "гана": "Ghana",
    "greece": "Greece",
    "греция": "Greece",
    "grenada": "Grenada",
    "гренада": "Grenada",
    "guatemala": "Guatemala",
    "гватемала": "Guatemala",
    "guinea": "Guinea",
    "гвинея": "Guinea",
    "guinea-bissau": "Guinea-Bissau",
    "гвинея-бисау": "Guinea-Bissau",
    "guyana": "Guyana",
    "гайана": "Guyana",
    "haiti": "Haiti",
    "гаити": "Haiti",
    "honduras": "Honduras",
    "гондурас": "Honduras",
    "hungary": "Hungary",
    "венгрия": "Hungary",
    "iceland": "Iceland",
    "исландия": "Iceland",
    "india": "India",
    "индия": "India",
    "indonesia": "Indonesia",
    "индонезия": "Indonesia",
    "iran": "Iran",
    "иран": "Iran",
    "iraq": "Iraq",
    "ирак": "Iraq",
    "croatia": "Croatia",
    "хорватия": "Croatia",
    "south africa": "South Africa",
    "юар": "South Africa",
    "dominican republic": "Dominican Republic",
    "доминиканская республика": "Dominican Republic",
    "bangladesh": "Bangladesh",
    "бангладеш": "Bangladesh",
    "monaco": "Monaco",
    "монако": "Monaco",
    "bashkortostan": "Bashkortostan",
    "buryatia": "Buryatia",
    "бурятия": "Buryatia",
    "chechnya": "Chechnya",
    "chuvashia": "Chuvashia",
    "чувашияrussia_ subjects. kgm": "Chuvashia",
    "dagestan": "Dagestan",
    "дагестан": "Dagestan",
    "ingushetia": "Ingushetia",
    "ингушетия": "Ingushetia",
    "kabardino-balkaria": "Kabardino-Balkaria",
    "кабардино- балкарияrussia_ subjects. kgm": "Kabardino-Balkaria",
    "kalmykia": "Kalmykia",
    "калмыкияrussia_ subjects. kgm": "Kalmykia",
    "karachay-cherkessia": "Karachay-Cherkessia",
    "карачаево- черкессияrussia_ subjects. kgm": "Karachay-Cherkessia",
    "karelia": "Karelia",
    "карелия!": "Karelia",
    "khakassia": "Khakassia",
    "хакассияrussia_ subjects. kgm": "Khakassia",
    "komi republic": "Komi Republic",
    "республика коми": "Komi Republic",
    "mari el": "Mari El",
    "мари- элrussia_ subjects. kgm": "Mari El",
    "mordovia": "Mordovia",
    "мордовия": "Mordovia",
    "north ossetia–alania": "North Ossetia–Alania",
    "северная осетия – алания": "North Ossetia–Alania",
    "sakha": "Sakha",
    "саха": "Sakha",
    "tatarstan": "Tatarstan",
    "tuva": "Tuva",
    "тува": "Tuva",
    "udmurtia": "Udmurtia",
    "удмуртия": "Udmurtia",
    "altai krai": "Altai Krai",
    "алтайский крайrussia_ subjects. kgm": "Altai Krai",
    "kamchatka krai": "Kamchatka Krai",
    "камчатский край": "Kamchatka Krai",
    "khabarovsk krai": "Khabarovsk Krai",
    "krasnodar krai": "Krasnodar Krai",
    "краснодарский край": "Krasnodar Krai",
    "krasnoyarsk krai": "Krasnoyarsk Krai",
    "красноярский край": "Krasnoyarsk Krai",
    "perm krai": "Perm Krai",
    "пермский край": "Perm Krai",
    "primorsky krai": "Primorsky Krai",
    "приморский край": "Primorsky Krai",
    "stavropol krai": "Stavropol Krai",
    "ставропольский край": "Stavropol Krai",
    "zabaykalsky krai": "Zabaykalsky Krai",
    "забайкальский крайrussia_ subjects. kgm": "Zabaykalsky Krai",
    "amur oblast": "Amur Oblast",
    "амурская область": "Amur Oblast",
    "arkhangelsk oblast": "Arkhangelsk Oblast",
    "архангельская область": "Arkhangelsk Oblast",
    "astrakhan oblast": "Astrakhan Oblast",
    "астраханская область": "Astrakhan Oblast",
    "belgorod oblast": "Belgorod Oblast",
    "белгородская область": "Belgorod Oblast",
    "alabama": "Alabama",
    "алабама": "Alabama",
    "alaska": "Alaska",
    "аляска": "Alaska",
    "arizona": "Arizona",
    "аризона": "Arizona",
    "arkansas": "Arkansas",
    "арканзас": "Arkansas",
    "california": "California",
    "калифорния": "California",
    "colorado": "Colorado",
    "колорадо": "Colorado",
    "connecticut": "Connecticut",
    "коннектикут": "Connecticut",
    "delaware": "Delaware",
    "делавэр": "Delaware",
    "florida": "Florida",
    "флорида": "Florida",
    "hawaii": "Hawaii",
    "гавайи": "Hawaii",
    "idaho": "Idaho",
    "айдахо": "Idaho",
    "illinois": "Illinois",
    "ииллинойс": "Illinois",
    "indiana": "Indiana",
    "индиана": "Indiana",
    "iowa": "Iowa",
    "айова": "Iowa",
    "kansas": "Kansas",
    "канзас": "Kansas",
    "kentucky": "Kentucky",
    "кентукки": "Kentucky",
    "louisiana": "Louisiana",
    "луизиана": "Louisiana",
    "maine": "Maine",
    "мэн": "Maine",
    "maryland": "Maryland",
    "мэриленд": "Maryland",
    "massachusetts": "Massachusetts",
    "массачусетс": "Massachusetts",
    "michigan": "Michigan",
    "мичиган": "Michigan",
    "minnesota": "Minnesota",
    "миннесота": "Minnesota",
    "mississippi": "Mississippi",
    "миссисипи": "Mississippi",
    "missouri": "Missouri",
    "миссури": "Missouri",
    "montana": "Montana",
    "монтана": "Montana",
    "nebraska": "Nebraska",
    "небраска": "Nebraska",
    "nevada": "Nevada",
    "невада": "Nevada",
    "new hampshire": "New Hampshire",
    "нью-гэмпшир": "New Hampshire",
    "new jersey": "New Jersey",
    "нью-джерси": "New Jersey",
    "new mexico": "New Mexico",
    "нью-мексико": "New Mexico",
    "new york": "New York",
    "нью-йорк": "New York",
    "north carolina": "North Carolina",
    "северная каролина": "North Carolina",
    "north dakota": "North Dakota",
    "северная дакота": "North Dakota",
    "ohio": "Ohio",
    "огайо": "Ohio",
    "oklahoma": "Oklahoma",
    "оклахома": "Oklahoma",
    "oregon": "Oregon",
    "орегон": "Oregon",
    "pennsylvania": "Pennsylvania",
    "пенсильвания": "Pennsylvania",
    "rhode island": "Rhode Island",
    "род-айленд": "Rhode Island",
    "south carolina": "South Carolina",
    "южная каролина": "South Carolina",
    "south dakota": "South Dakota",
    "южная дакота": "South Dakota",
    "tennessee": "Tennessee",
    "теннесси": "Tennessee",
    "texas": "Texas",
    "техас": "Texas",
    "utah": "Utah",
    "юта": "Utah",
    "vermont": "Vermont",
    "вермонт": "Vermont",
    "virginia": "Virginia",
    "виргиния": "Virginia",
    "washington": "Washington",
    "вашингтон": "Washington",
    "west virginia": "West Virginia",
    "западная виргиния": "West Virginia",
    "wisconsin": "Wisconsin",
    "висконсин": "Wisconsin",
    "wyoming": "Wyoming",
    "вайоминг": "Wyoming",
    "bryansk oblast": "Bryansk Oblast",
    "брянская область": "Bryansk Oblast",
    "chelyabinsk oblast": "Chelyabinsk Oblast",
    "челябинская область": "Chelyabinsk Oblast",
    "irkutsk oblast": "Irkutsk Oblast",
    "иркутская": "Irkutsk Oblast",
    "ivanovo oblast": "Ivanovo Oblast",
    "ивановская область": "Ivanovo Oblast",
    "kaliningrad oblast": "Kaliningrad Oblast",
    "калининградская область": "Kaliningrad Oblast",
    "kaluga oblast": "Kaluga Oblast",
    "калужской области": "Kaluga Oblast",
    "kemerovo oblast": "Kemerovo Oblast",
    "кемеровской областью": "Kemerovo Oblast",
    "kirov oblast": "Kirov Oblast",
    "кировская область": "Kirov Oblast",
    "kostroma oblast": "Kostroma Oblast",
    "костромская область": "Kostroma Oblast",
    "kurgan oblast": "Kurgan Oblast",
    "курганская область": "Kurgan Oblast",
    "kursk oblast": "Kursk Oblast",
    "курская область": "Kursk Oblast",
    "leningrad oblast": "Leningrad Oblast",
    "ленинградская область": "Nizhny Novgorod Oblast",
    "lipetsk oblast": "Lipetsk Oblast",
    "липецкая область": "Lipetsk Oblast",
    "magadan oblast": "Magadan Oblast",
    "магаданская область": "Magadan Oblast",
    "moscow oblast": "Moscow Oblast",
    "московская область": "Moscow Oblast",
    "murmansk oblast": "Murmansk Oblast",
    "мурманская область": "Murmansk Oblast",
    "nizhny novgorod oblast": "Nizhny Novgorod Oblast",
    "novgorod oblast": "Novgorod Oblast",
    "новгородская область": "Novgorod Oblast",
    "novosibirsk oblast": "Novosibirsk Oblast",
    "новосибирская область": "Novosibirsk Oblast",
    "omsk oblast": "Omsk Oblast",
    "омская область": "Omsk Oblast",
    "orenburg oblast": "Orenburg Oblast",
    "оренбургская область": "Orenburg Oblast",
    "oryol oblast": "Oryol Oblast",
    "орловская область": "Oryol Oblast",
    "penza oblast": "Penza Oblast",
    "пензенская область": "Penza Oblast",
    "pskov oblast": "Pskov Oblast",
    "псковская область": "Pskov Oblast",
    "rostov oblast": "Rostov Oblast",
    "ростовская область, ": "Rostov Oblast",
    "ryazan oblast": "Ryazan Oblast",
    "рязанская область": "Ryazan Oblast",
    "sakhalin oblast": "Sakhalin Oblast",
    "сахалинская область": "Sakhalin Oblast",
    "samara oblast": "Samara Oblast",
    "самарская область": "Samara Oblast",
    "saratov oblast": "Saratov Oblast",
    "саратовская область": "Saratov Oblast",
    "smolensk oblast": "Smolensk Oblast",
    "смоленская область": "Smolensk Oblast",
    "sverdlovsk oblast": "Sverdlovsk Oblast",
    "свердловская область": "Sverdlovsk Oblast",
    "tambov oblast": "Tambov Oblast",
    "тамбовская область": "Tambov Oblast",
    "tomsk oblast": "Tomsk Oblast",
    "томская область": "Tomsk Oblast",
    "tula oblast": "Tula Oblast",
    "тульская область": "Tula Oblast",
    "tver oblast": "Tver Oblast",
    "тверская область": "Tver Oblast",
    "tyumen oblast": "Tyumen Oblast",
    "тюменской области": "Tyumen Oblast",
    "ulyanovsk oblast": "Ulyanovsk Oblast",
    "ульяновская область": "Ulyanovsk Oblast",
    "vladimir oblast": "Vladimir Oblast",
    "владимирская область": "Vladimir Oblast",
    "volgograd oblast": "Volgograd Oblast",
    "волгоградская область": "Volgograd Oblast",
    "vologda oblast": "Vologda Oblast",
    "вологодская область": "Vologda Oblast",
    "voronezh oblast": "Voronezh Oblast",
    "воронежская область": "Voronezh Oblast",
    "yaroslavl oblast": "Yaroslavl Oblast",
    "ярославская область": "Yaroslavl Oblast",
    "jewish autonomous oblast": "Jewish Autonomous Oblast",
    "еврейская автономная область": "Jewish Autonomous Oblast",
    "chukotka autonomous okrug": "Chukotka Autonomous Okrug",
    "чукотский автономный округ": "Chukotka Autonomous Okrug",
    "khanty–mansi autonomous okrug": "Khanty–Mansi Autonomous Okrug",
    "ханты-мансийский автономный округ": "Khanty–Mansi Autonomous Okrug",
    "nenetsautonomous okrug": "NenetsAutonomous Okrug",
    "ненецкий автономный округ": "NenetsAutonomous Okrug",
    "yamalo-nenets autonomous okrug": "Yamalo-Nenets Autonomous Okrug",
    "ямало-ненецкий автономный округ": "Yamalo-Nenets Autonomous Okrug",
    "moscow": "Moscow",
    "москва": "Moscow",
    "saint petersburg": "Saint Petersburg",
    "санкт-петербург": "Saint Petersburg",
    "cherkasy oblast": "Cherkasy Oblast",
    "черкасская область": "Cherkasy Oblast",
    "chernivtsi oblast": "Chernivtsi Oblast",
    "черновицкая область": "Chernivtsi Oblast",
    "chernihiv oblast": "Chernihiv Oblast",
    "черниговская область": "Chernihiv Oblast",
    "dnipropetrovsk oblast": "Dnipropetrovsk Oblast",
    "днепропетровская область": "Dnipropetrovsk Oblast",
    "donetsk oblast": "Donetsk Oblast",
    "донецкая область": "Donetsk Oblast",
    "ivano-frankivsk oblast": "Ivano-Frankivsk Oblast",
    "ивано-франковская область": "Ivano-Frankivsk Oblast",
    "kharkiv oblast": "Kharkiv Oblast",
    "харьковская область": "Kharkiv Oblast",
    "kherson oblast": "Kherson Oblast",
    "херсонская область": "Kherson Oblast",
    "khmelnytskyi oblast": "Khmelnytskyi Oblast",
    "хмельницкая область": "Khmelnytskyi Oblast",
    "kirovohrad oblast": "Kirovohrad Oblast",
    "кировоградская область": "Kirovohrad Oblast",
    "kyiv oblast": "Kyiv Oblast",
    "киевская область": "Kyiv Oblast",
    "luhansk oblast": "Luhansk Oblast",
    "луганская область": "Luhansk Oblast",
    "lviv oblast": "Lviv Oblast",
    "львовская область": "Lviv Oblast",
    "mykolaiv oblast": "Mykolaiv Oblast",
    "николаевская область": "Mykolaiv Oblast",
    "odesa oblast": "Odesa Oblast",
    "одесская область": "Odesa Oblast",
    "poltava oblast": "Poltava Oblast",
    "полтавская область": "Poltava Oblast",
    "rivne oblast": "Rivne Oblast",
    "ровенская область": "Rivne Oblast",
    "sumy oblast": "Sumy Oblast",
    "сумская область": "Sumy Oblast",
    "ternopil oblast": "Ternopil Oblast",
    "тернопольская область": "Ternopil Oblast",
    "vinnytsia oblast": "Vinnytsia Oblast",
    "винницкая область": "Vinnytsia Oblast",
    "volyn oblast": "Volyn Oblast",
    "волынская область": "Volyn Oblast",
    "zaporizhia oblast": "Zaporizhia Oblast",
    "запорожская область": "Zaporizhia Oblast",
    "zakarpattia oblast": "Zakarpattia Oblast",
    "закарпатская область": "Zakarpattia Oblast",
    "zhytomyr oblast": "Zhytomyr Oblast",
    "житомирская область": "Zhytomyr Oblast",
    "crimea": "Crimea",
    "крым": "Crimea",
    "kyiv": "Kyiv",
    "киев": "Kyiv",
    "sevastopol": "Sevastopol",
    "севастополь": "Sevastopol",
    "israel": "Israel",
    "израиль": "Israel",
    "kuwait": "Kuwait",
    "кувейт": "Kuwait",
    "minsk city": "Minsk City",
    "минск": "Minsk City",
    "brest region": "Brest Region",
    "брестская область": "Brest Region",
    "gomel region": "Gomel Region",
    "гомельская область": "Gomel Region",
    "grodno region": "Grodno Region",
    "гродненская область": "Grodno Region",
    "ireland": "Ireland",
    "ирландия": "Ireland",
    "italy": "Italy",
    "италия": "Italy",
    "ivory coast": "Ivory Coast",
    "кот-д'ивуар": "Ivory Coast",
    "jamaica": "Jamaica",
    "ямайка": "Jamaica",
    "japan": "Japan",
    "япония": "Japan",
    "jordan": "Jordan",
    "иордания": "Jordan",
    "kazakhstan": "Kazakhstan",
    "казахстан": "Kazakhstan",
    "kenya": "Kenya",
    "кения": "Kenya",
    "kiribati": "Kiribati",
    "кирибати": "Kiribati",
    "kyrgyzstan": "Kyrgyzstan",
    "кыргызстан": "Kyrgyzstan",
    "laos": "Laos",
    "лаос": "Laos",
    "latvia": "Latvia",
    "латвия": "Latvia",
    "lebanon": "Lebanon",
    "ливан": "Lebanon",
    "lesotho": "Lesotho",
    "лесото": "Lesotho",
    "liberia": "Liberia",
    "либерия": "Liberia",
    "libya": "Libya",
    "ливия": "Libya",
    "liechtenstein": "Liechtenstein",
    "лихтенштейн": "Liechtenstein",
    "lithuania": "Lithuania",
    "литва": "Lithuania",
    "luxembourg": "Luxembourg",
    "люксембург": "Luxembourg",
    "madagascar": "Madagascar",
    "мадагаскар": "Madagascar",
    "malawi": "Malawi",
    "малави": "Malawi",
    "malaysia": "Malaysia",
    "малайзия": "Malaysia",
    "maldives": "Maldives",
    "мальдивы": "Maldives",
    "mali": "Mali",
    "мали": "Mali",
    "malta": "Malta",
    "мальта": "Malta",
    "marshall islands": "Marshall Islands",
    "маршалловы острова": "Marshall Islands",
    "mauritania": "Mauritania",
    "мавритания": "Mauritania",
    "mauritius": "Mauritius",
    "маврикий": "Mauritius",
    "mexico": "Mexico",
    "мексика": "Mexico",
    "micronesia": "Micronesia",
    "микронезия": "Micronesia",
    "moldova": "Moldova",
    "молдова": "Moldova",
    "mogilev region": "Mogilev Region",
    "могилевская область": "Mogilev Region",
    "minsk region": "Minsk Region",
    "минская область": "Minsk Region",
    "vitebsk region": "Vitebsk Region",
    "витебская область": "Vitebsk Region",
    "mongolia": "Mongolia",
    "монголия": "Mongolia",
    "montenegro": "Montenegro",
    "черногория": "Montenegro",
    "morocco": "Morocco",
    "марокко": "Morocco",
    "mozambique": "Mozambique",
    "мозамбик": "Mozambique",
    "myanmar": "Myanmar",
    "мьянма": "Myanmar",
    "namibia": "Namibia",
    "намибия": "Namibia",
    "nauru": "Nauru",
    "науру": "Nauru",
    "nepal": "Nepal",
    "непал": "Nepal",
    "netherlands": "Netherlands",
    "нидерланды": "Netherlands",
    "new zealand": "New Zealand",
    "новая зеландия": "New Zealand",
    "nicaragua": "Nicaragua",
    "никарагуа": "Nicaragua",
    "niger": "Niger",
    "нигер": "Niger",
    "nigeria": "Nigeria",
    "нигерия": "Nigeria",
    "north korea": "North Korea",
    "северная корея": "North Korea",
    "north macedonia": "North Macedonia",
    "северная македония": "North Macedonia",
    "norway": "Norway",
    "норвегия": "Norway",
    "oman": "Oman",
    "оман": "Oman",
    "pakistan": "Pakistan",
    "пакистан": "Pakistan",
    "palau": "Palau",
    "палау": "Palau",
    "palestine": "Palestine",
    "палестина": "Palestine",
    "panama": "Panama",
    "панама": "Panama",
    "papua new guinea": "Papua New Guinea",
    "папуа-новая гвинея": "Papua New Guinea",
    "paraguay": "Paraguay",
    "парагвай": "Paraguay",
    "peru": "Peru",
    "перу": "Peru",
    "philippines": "Philippines",
    "филиппины": "Philippines",
    "poland": "Poland",
    "польша": "Poland",
    "portugal": "Portugal",
    "португалия": "Portugal",
    "qatar": "Qatar",
    "катар": "Qatar",
    "romania": "Romania",
    "румыния": "Romania",
    "russia": "Russia",
    "россия": "Russia",
    "rwanda": "Rwanda",
    "руанда": "Rwanda",
    "saint kitts and nevis": "Saint Kitts and Nevis",
    "сент-китс и невис": "Saint Kitts and Nevis",
    "saint lucia": "Saint Lucia",
    "сент-люсия": "Saint Lucia",
    "saint vincent and the grenadines": "Saint Vincent and the Grenadines",
    "сент-винсент и гренадины": "Saint Vincent and the Grenadines",
    "samoa": "Samoa",
    "самоа": "Samoa",
    "san marino": "San Marino",
    "сан-марино": "San Marino",
    "são tomé and príncipe": "São Tomé and Príncipe",
    "сан-томе и принсипи": "São Tomé and Príncipe",
    "saudi arabia": "Saudi Arabia",
    "саудовская аравия": "Saudi Arabia",
    "senegal": "Senegal",
    "сенегал": "Senegal",
    "serbia": "Serbia",
    "сербия": "Serbia",
    "seychelles": "Seychelles",
    "сейшельские о-ва": "Seychelles",
    "sierra leone": "Sierra Leone",
    "сьерра-леоне": "Sierra Leone",
    "singapore": "Singapore",
    "сингапур": "Singapore",
    "slovakia": "Slovakia",
    "словакия": "Slovakia",
    "slovenia": "Slovenia",
    "словения": "Slovenia",
    "solomon islands": "Solomon Islands",
    "соломоновы о-ва": "Solomon Islands",
    "somalia": "Somalia",
    "сомали": "Somalia",
    "south korea": "South Korea",
    "южная корея": "South Korea",
    "south sudan": "South Sudan",
    "южный судан": "South Sudan",
    "spain": "Spain",
    "испания": "Spain",
    "sri lanka": "Sri Lanka",
    "шри-ланка": "Sri Lanka",
    "sudan": "Sudan",
    "судан": "Sudan",
    "suriname": "Suriname",
    "суринам": "Suriname",
    "sweden": "Sweden",
    "швеция": "Sweden",
    "switzerland": "Switzerland",
    "швейцария": "Switzerland",
    "syria": "Syria",
    "сирия": "Syria",
    "tajikistan": "Tajikistan",
    "таджикистан": "Tajikistan",
    "tanzania": "Tanzania",
    "танзания": "Tanzania",
    "thailand": "Thailand",
    "таиланд": "Thailand",
    "timor-leste": "Timor-Leste",
    "восточный тимор": "Timor-Leste",
    "togo": "Togo",
    "того": "Togo",
    "tonga": "Tonga",
    "тонга": "Tonga",
    "trinidad and tobago": "Trinidad and Tobago",
    "тринидад и тобаго": "Trinidad and Tobago",
    "tunisia": "Tunisia",
    "тунис": "Tunisia",
    "turkey": "Turkey",
    "турция": "Turkey",
    "turkmenistan": "Turkmenistan",
    "туркменистан": "Turkmenistan",
    "tuvalu": "Tuvalu",
    "тувалу": "Tuvalu",
    "uganda": "Uganda",
    "уганда": "Uganda",
    "ukraine": "Ukraine",
    "украина": "Ukraine",
    "united arab emirates": "United Arab Emirates",
    "объединенные арабские эмираты": "United Arab Emirates",
    "united kingdom": "United Kingdom",
    "великобритания": "United Kingdom",
    "uk": "United Kingdom",
    "united states": "United States",
    "соединенные штаты америки": "United States",
    "usa": "United States",
    "us": "United States",
    "сша": "United States",
    "соединенные штаты": "United States",
    "uruguay": "Uruguay",
    "уругвай": "Uruguay",
    "uzbekistan": "Uzbekistan",
    "узбекистан": "Uzbekistan",
    "vanuatu": "Vanuatu",
    "вануату": "Vanuatu",
    "vatican city": "Vatican City",
    "ватикан": "Vatican City",
    "venezuela": "Venezuela",
    "венесуэла": "Venezuela",
    "vietnam": "Vietnam",
    "вьетнам": "Vietnam",
    "yemen": "Yemen",
    "йемен": "Yemen",
    "zambia": "Zambia",
    "замбия": "Zambia",
    "abkhazia": "Abkhazia",
    "абхазия": "Abkhazia",
    "kosovo": "Kosovo",
    "косово": "Kosovo",
    "northern cyprus": "Northern Cyprus",
    "северный кипр": "Northern Cyprus",
    "sahrawi arab democratic republic": "Sahrawi Arab Democratic Republic",
    "сахарская арабская демократическая республика": "Sahrawi Arab Democratic Republic",
    "сахарская республика": "Sahrawi Arab Democratic Republic",
    "сахара": "Sahrawi Arab Democratic Republic",
    "сахарская АДР": "Sahrawi Arab Democratic Republic",
    "south ossetia": "South Ossetia",
    "южная осетия": "South Ossetia",
    "taiwan": "Taiwan",
    "тайвань": "Taiwan",
    "transnistria": "Transnistria",
    "приднестровская молдавская республика": "Transnistria",
    "приднестровье": "Transnistria",
    "somaliland": "Somaliland",
    "сомалиленд": "Somaliland",
    "zimbabwe": "Zimbabwe",
    "зимбабве": "Zimbabwe",
}

# ЗАМЕНЕНО НА АКТУАЛЬНЫЙ ВАРИАНТ 8/9/25
# answer_map = {
#     "colombia": "Colombia",
#     "колумбия": "Colombia",
#     "turkey": "Turkey",
#     "турция": "Turkey",
#     "india": "India",
#     "индия": "India",
#     "afghanistan": "Afghanistan",
#     "афганистан": "Afghanistan",
#     "albania": "Albania",
#     "албания": "Albania",
#     "angola": "Angola",
#     "ангола": "Angola",
#     "antigua and barbuda": "Antigua and Barbuda",
#     "антигуа и барбуда": "Antigua and Barbuda",
#     "argentina": "Argentina",
#     "аргентина": "Argentina",
#     "armenia": "Armenia",
#     "армения": "Armenia",
#     "aruba": "Aruba",
#     "аруба": "Aruba",
#     "austria": "Austria",
#     "австрия": "Austria",
#     "azerbaijan": "Azerbaijan",
#     "азербайджан": "Azerbaijan",
#     "bahamas": "Bahamas",
#     "багамские острова": "Bahamas",
#     "barbados": "Barbados",
#     "барбадос": "Barbados",
#     "belarus": "Belarus",
#     "беларусь": "Belarus",
#     "belgium": "Belgium",
#     "бельгия": "Belgium",
#     "belize": "Belize",
#     "белиз": "Belize",
#     "benin": "Benin",
#     "бенин": "Benin",
#     "bolivia": "Bolivia",
#     "боливия": "Bolivia",
#     "bosnia and herzegovina": "Bosnia and Herzegovina",
#     "босния и герцеговина": "Bosnia and Herzegovina",
#     "botswana": "Botswana",
#     "ботсвана": "Botswana",
#     "brunei": "Brunei",
#     "бруней": "Brunei",
#     "burundi": "Burundi",
#     "бурунди": "Burundi",
#     "cabo verde": "Cabo Verde",
#     "кабо верде": "Cabo Verde",
#     "cambodia": "Cambodia",
#     "камбоджа": "Cambodia",
#     "cameroon": "Cameroon",
#     "камерун": "Cameroon",
#     "canada": "Canada",
#     "канада": "Canada",
#     "central african republic": "Central African Republic",
#     "центральная африканская республика": "Central African Republic",
#     "центрально африканская республика": "Central African Republic",
#     "цар": "Central African Republic",
#     "bangladesh": "Bangladesh",
#     "бангладеш": "Bangladesh",
#     "algeria": "Algeria",
#     "алжир": "Algeria",
#     "andorra": "Andorra",
#     "андорра": "Andorra",
#     "australia": "Australia",
#     "австралия": "Australia",
#     "brazil": "Brazil",
#     "бразилия": "Brazil",
#     "bahrain": "Bahrain",
#     "бахрейн": "Bahrain",
#     "bhutan": "Bhutan",
#     "бутан": "Bhutan",
#     "chad": "Chad",
#     "чад": "Chad",
#     "chile": "Chile",
#     "чили": "Chile",
#     "china": "China",
#     "китай": "China",
#     "comoros": "Comoros",
#     "коморос": "Comoros",
#     "congo": "Congo",
#     "конго": "Congo",
#     "congo (democratic republic)": "Democratic Republic of the Congo",
#     "конго (демократическая республика)": "Democratic Republic of the Congo",
#     "democratic republic of congo": "Democratic Republic of the Congo",
#     "democratic republic of the congo": "Democratic Republic of the Congo",
#     "демократическая республика конго": "Democratic Republic of the Congo",
#     "costa rica": "Costa Rica",
#     "коста-рика": "Costa Rica",
#     "коста рика": "Costa Rica",
#     "костарика": "Costa Rica",
#     "cuba": "Cuba",
#     "куба": "Cuba",
#     "cyprus": "Cyprus",
#     "кипр": "Cyprus",
#     "djibouti": "Djibouti",
#     "джибути": "Djibouti",
#     "dominica": "Dominica",
#     "доминика": "Dominica",
#     "east timor": "East Timor",
#     "восточный тимор": "East Timor",
#     "ecuador": "Ecuador",
#     "эквадор": "Ecuador",
#     "egypt": "Egypt",
#     "египет": "Egypt",
#     "el salvador": "El Salvador",
#     "сальвадор": "El Salvador",
#     "эль сальвадор": "El Salvador",
#     "equatorial guinea": "Equatorial Guinea",
#     "экваториальная гвинея": "Equatorial Guinea",
#     "eritrea": "Eritrea",
#     "эритрея": "Eritrea",
#     "estonia": "Estonia",
#     "эстония": "Estonia",
#     "eswatini": "Eswatini",
#     "эсватини": "Eswatini",
#     "ethiopia": "Ethiopia",
#     "эфиопия": "Ethiopia",
#     "fiji": "Fiji",
#     "фиджи": "Fiji",
#     "finland": "Finland",
#     "финляндия": "Finland",
#     "gabon": "Gabon",
#     "габон": "Gabon",
#     "gambia": "Gambia",
#     "гамбия": "Gambia",
#     "czech republic": "Czech Republic",
#     "czechia": "Czech Republic",
#     "czech": "Czech Republic",
#     "чешская республика": "Czech Republic",
#     "чехия": "Czech Republic",
#     "dominican republic": "Dominican Republic",
#     "доминиканская республика": "Dominican Republic",
#     "germany": "Germany",
#     "германия": "Germany",
#     "ghana": "Ghana",
#     "гана": "Ghana",
#     "greece": "Greece",
#     "греция": "Greece",
#     "grenada": "Grenada",
#     "гренада": "Grenada",
#     "guinea": "Guinea",
#     "гвинея": "Guinea",
#     "guinea-bissau": "Guinea-Bissau",
#     "гвинея-бисау": "Guinea-Bissau",
#     "france": "France",
#     "франция": "France",
#     "guatemala": "Guatemala",
#     "гватемала": "Guatemala",
#     "croatia": "Croatia",
#     "хорватия": "Croatia",
#     "guyana": "Guyana",
#     "гайана": "Guyana",
#     "haiti": "Haiti",
#     "гаити": "Haiti",
#     "honduras": "Honduras",
#     "гондурас": "Honduras",
#     "hungary": "Hungary",
#     "венгрия": "Hungary",
#     "iceland": "Iceland",
#     "исландия": "Iceland",
#     "indonesia": "Indonesia",
#     "индонезия": "Indonesia",
#     "iraq": "Iraq",
#     "ирак": "Iraq",
#     "israel": "Israel",
#     "израиль": "Israel",
#     "italy": "Italy",
#     "италия": "Italy",
#     "jamaica": "Jamaica",
#     "ямайка": "Jamaica",
#     "japan": "Japan",
#     "япония": "Japan",
#     "jordan": "Jordan",
#     "иордания": "Jordan",
#     "kazakhstan": "Kazakhstan",
#     "казахстан": "Kazakhstan",
#     "kuwait": "Kuwait",
#     "кувейт": "Kuwait",
#     "kyrgyzstan": "Kyrgyzstan",
#     "кыргизстан": "Kyrgyzstan",
#     "laos": "Laos",
#     "лаос": "Laos",
#     "lebanon": "Lebanon",
#     "ливан": "Lebanon",
#     "lesotho": "Lesotho",
#     "лесото": "Lesotho",
#     "libya": "Libya",
#     "ливия": "Libya",
#     "liechtenstein": "Liechtenstein",
#     "лихтенштейн": "Liechtenstein",
#     "lithuania": "Lithuania",
#     "литва": "Lithuania",
#     "luxembourg": "Luxembourg",
#     "люксембург": "Luxembourg",
#     "madagascar": "Madagascar",
#     "мадагаскар": "Madagascar",
#     "malawi": "Malawi",
#     "малави": "Malawi",
#     "malaysia": "Malaysia",
#     "малайзия": "Malaysia",
#     "maldives": "Maldives",
#     "мальдивы": "Maldives",
#     "mali": "Mali",
#     "мали": "Mali",
#     "ireland": "Ireland",
#     "ирландия": "Ireland",
#     "kiribati": "Kiribati",
#     "кирибати": "Kiribati",
#     "iran": "Iran",
#     "иран": "Iran",
#     "marshall islands": "Marshall Islands",
#     "маршалл острова": "Marshall Islands",
#     "mauritania": "Mauritania",
#     "мавритания": "Mauritania",
#     "mauritius": "Mauritius",
#     "маврикий": "Mauritius",
#     "liberia": "Liberia",
#     "либерия": "Liberia",
#     "latvia": "Latvia",
#     "латвия": "Latvia",
#     "malta": "Malta",
#     "мальта": "Malta",
#     "mexico": "Mexico",
#     "мексика": "Mexico",
#     "micronesia": "Micronesia",
#     "микронезия": "Micronesia",
#     "moldova": "Moldova",
#     "молдова": "Moldova",
#     "monaco": "Monaco",
#     "монако": "Monaco",
#     "mongolia": "Mongolia",
#     "монголия": "Mongolia",
#     "montenegro": "Montenegro",
#     "черногория": "Montenegro",
#     "morocco": "Morocco",
#     "марокко": "Morocco",
#     "mozambique": "Mozambique",
#     "мозамбик": "Mozambique",
#     "myanmar": "Myanmar",
#     "мьянма": "Myanmar",
#     "namibia": "Namibia",
#     "намибия": "Namibia",
#     "nauru": "Nauru",
#     "науру": "Nauru",
#     "nepal": "Nepal",
#     "непал": "Nepal",
#     "new zealand": "New Zealand",
#     "новая зеландия": "New Zealand",
#     "nicaragua": "Nicaragua",
#     "никарагуа": "Nicaragua",
#     "niger": "Niger",
#     "нигер": "Niger",
#     "nigeria": "Nigeria",
#     "нигерия": "Nigeria",
#     "north korea": "North Korea",
#     "северная корея": "North Korea",
#     "norway": "Norway",
#     "норвегия": "Norway",
#     "oman": "Oman",
#     "оман": "Oman",
#     "pakistan": "Pakistan",
#     "пакистан": "Pakistan",
#     "palau": "Palau",
#     "палау": "Palau",
#     "panama": "Panama",
#     "панама": "Panama",
#     "paraguay": "Paraguay",
#     "парагвай": "Paraguay",
#     "peru": "Peru",
#     "перу": "Peru",
#     "philippines": "Philippines",
#     "филиппины": "Philippines",
#     "poland": "Poland",
#     "польша": "Poland",
#     "portugal": "Portugal",
#     "португалия": "Portugal",
#     "qatar": "Qatar",
#     "катар": "Qatar",
#     "romania": "Romania",
#     "румыния": "Romania",
#     "russia": "Russia",
#     "россия": "Russia",
#     "rwanda": "Rwanda",
#     "руанда": "Rwanda",
#     "saint kitts and nevis": "Saint Kitts and Nevis",
#     "saint kitts": "Saint Kitts and Nevis",
#     "nevis": "Saint Kitts and Nevis",
#     "сент-китс и невис": "Saint Kitts and Nevis",
#     "сент китс и невис": "Saint Kitts and Nevis",
#     "сенткитс и невис": "Saint Kitts and Nevis",
#     "сенткитс": "Saint Kitts and Nevis",
#     "невис": "Saint Kitts and Nevis",
#     "saint lucia": "Saint Lucia",
#     "святая люсия": "Saint Lucia",
#     "netherlands": "Netherlands",
#     "нидерланды": "Netherlands",
#     "north macedonia": "North Macedonia",
#     "северная македония": "North Macedonia",
#     "saint vincent and the grenadines": "Saint Vincent and the Grenadines",
#     "сент-винсент и гренадины": "Saint Vincent and the Grenadines",
#     "san marino": "San Marino",
#     "сан-марино": "San Marino",
#     "sao tome and principe": "Sao Tome and Principe",
#     "sao tome и principe": "Sao Tome and Principe",
#     "senegal": "Senegal",
#     "сенегал": "Senegal",
#     "serbia": "Serbia",
#     "сербия": "Serbia",
#     "seychelles": "Seychelles",
#     "сейшельские острова": "Seychelles",
#     "sierra leone": "Sierra Leone",
#     "сьерра-леоне": "Sierra Leone",
#     "singapore": "Singapore",
#     "сингапур": "Singapore",
#     "slovakia": "Slovakia",
#     "словакия": "Slovakia",
#     "slovenia": "Slovenia",
#     "словения": "Slovenia",
#     "solomon islands": "Solomon Islands",
#     "соломонские острова": "Solomon Islands",
#     "south africa": "South Africa",
#     "юар": "South Africa",
#     "south korea": "South Korea",
#     "южная корея": "South Korea",
#     "south sudan": "South Sudan",
#     "южный судан": "South Sudan",
#     "taiwan": "Taiwan",
#     "тайвань": "Taiwan",
#     "tajikistan": "Tajikistan",
#     "таджикистан": "Tajikistan",
#     "tanzania": "Tanzania",
#     "танзания": "Tanzania",
#     "thailand": "Thailand",
#     "таиланд": "Thailand",
#     "togo": "Togo",
#     "того": "Togo",
#     "tonga": "Tonga",
#     "тонга": "Tonga",
#     "trinidad and tobago": "Trinidad and Tobago",
#     "тринидад и тобаго": "Trinidad and Tobago",
#     "tunisia": "Tunisia",
#     "тунис": "Tunisia",
#     "turkmenistan": "Turkmenistan",
#     "туркменистан": "Turkmenistan",
#     "tuvalu": "Tuvalu",
#     "тувалу": "Tuvalu",
#     "uganda": "Uganda",
#     "уганда": "Uganda",
#     "ukraine": "Ukraine",
#     "украина": "Ukraine",
#     "united arab emirates": "United Arab Emirates",
#     "объединенные арабские эмираты": "United Arab Emirates",
#     "united kingdom": "United Kingdom",
#     "великобритания": "United Kingdom",
#     "uruguay": "Uruguay",
#     "уругвай": "Uruguay",
#     "uzbekistan": "Uzbekistan",
#     "узбекистан": "Uzbekistan",
#     "vanuatu": "Vanuatu",
#     "вануату": "Vanuatu",
#     "saudi arabia": "Saudi Arabia",
#     "саудовская аравия": "Saudi Arabia",
#     "united states": "United States",
#     "us": "United States",
#     "usa": "United States",
#     "соединенные штаты": "United States",
#     "somalia": "Somalia",
#     "сомали": "Somalia",
#     "vatican city": "Vatican City",
#     "ватикан": "Vatican City",
#     "venezuela": "Venezuela",
#     "венесуэла": "Venezuela",
#     "vietnam": "Vietnam",
#     "вьетнам": "Vietnam",
#     "yemen": "Yemen",
#     "йемен": "Yemen",
#     "zambia": "Zambia",
#     "замбия": "Zambia",
#     "zimbabwe": "Zimbabwe",
#     "зимбабве": "Zimbabwe",
#     "denmark": "Denmark",
#     "дания": "Denmark",
#     "burkina faso": "Burkina Faso",
#     "буркина фасо": "Burkina Faso",
#     "samoa": "Samoa",
#     "самоа": "Samoa",
#     "kenya": "Kenya",
#     "кения": "Kenya",
#     "bulgaria": "Bulgaria",
#     "болгария": "Bulgaria",
#     "georgia": "Georgia",
#     "грузия": "Georgia",
#     "papua new guinea": "Papua New Guinea",
#     "папуа новая гвинея": "Papua New Guinea",
# }
