version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flagsguess
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    # optional if you want logs
    tty: true

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./client/.env

volumes:
  postgres_data:
