services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file:
      - server/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: flags
      POSTGRES_PASSWORD: flags123
      POSTGRES_DB: guessflags
    ports:
      - "5432:5432"
