export const answer_map: Record<string, string> = {
  afghanistan: "Afghanistan",
  афганистан: "Afghanistan",
  albania: "Albania",
  албания: "Albania",
  algeria: "Algeria",
  алжир: "Algeria",
  andorra: "Andorra",
  андорра: "Andorra",
  angola: "Angola",
  ангола: "Angola",
  "antigua and barbuda": "Antigua and Barbuda",
  "антигуа и барбуда": "Antigua and Barbuda",
  argentina: "Argentina",
  аргентина: "Argentina",
  armenia: "Armenia",
  армения: "Armenia",
  australia: "Australia",
  австралия: "Australia",
  austria: "Austria",
  австрия: "Austria",
  azerbaijan: "Azerbaijan",
  азербайджан: "Azerbaijan",
  "the bahamas": "The Bahamas",
  багамы: "The Bahamas",
  bahrain: "Bahrain",
  бахрейн: "Bahrain",
  adygea: "Adygea",
  адыгея: "Adygea",
  barbados: "Barbados",
  барбадос: "Barbados",
  belgium: "Belgium",
  бельгия: "Belgium",
  belize: "Belize",
  белиз: "Belize",
  benin: "Benin",
  бенин: "Benin",
  bhutan: "Bhutan",
  бутан: "Bhutan",
  bolivia: "Bolivia",
  боливия: "Bolivia",
  "bosnia and herzegovina": "Bosnia and Herzegovina",
  "босния и герцеговина": "Bosnia and Herzegovina",
  botswana: "Botswana",
  ботсвана: "Botswana",
  brazil: "Brazil",
  бразилия: "Brazil",
  brunei: "Brunei",
  бруней: "Brunei",
  bulgaria: "Bulgaria",
  болгария: "Bulgaria",
  "burkina faso": "Burkina Faso",
  "буркина-фасо": "Burkina Faso",
  burundi: "Burundi",
  бурунди: "Burundi",
  cambodia: "Cambodia",
  камбоджа: "Cambodia",
  cameroon: "Cameroon",
  камерун: "Cameroon",
  canada: "Canada",
  канада: "Canada",
  "cape verde": "Cape Verde",
  "кабо-верде": "Cape Verde",
  "central african republic": "Central African Republic",
  "центральноафриканская республика": "Central African Republic",
  цар: "Central African Republic",
  car: "Central African Republic",
  "центрально африканская республика": "Central African Republic",
  chad: "Chad",
  чад: "Chad",
  chile: "Chile",
  чили: "Chile",
  china: "China",
  кнр: "China",
  colombia: "Colombia",
  колумбия: "Colombia",
  comoros: "Comoros",
  "коморские острова": "Comoros",
  "democratic republic of the congo": "Democratic Republic of the Congo",
  "демократическая республика конго": "Democratic Republic of the Congo",
  belarus: "Belarus",
  беларусь: "Belarus",
  "republic of the congo": "Republic of the Congo",
  "республика конго": "Republic of the Congo",
  "costa rica": "Costa Rica",
  "коста-рика": "Costa Rica",
  cuba: "Cuba",
  куба: "Cuba",
  cyprus: "Cyprus",
  кипр: "Cyprus",
  "czech republic": "Czech Republic",
  "чешская республика": "Czech Republic",
  czechia: "Czech Republic",
  чечня: "Chechnya",
  denmark: "Denmark",
  дания: "Denmark",
  djibouti: "Djibouti",
  джибути: "Djibouti",
  dominica: "Dominica",
  доминика: "Dominica",
  "altai republic": "Altai Republic",
  "республика алтай": "Altai Republic",
  ecuador: "Ecuador",
  эквадор: "Ecuador",
  egypt: "Egypt",
  египет: "Egypt",
  "el salvador": "El Salvador",
  сальвадор: "El Salvador",
  "equatorial guinea": "Equatorial Guinea",
  "экваториальная гвинея": "Equatorial Guinea",
  eritrea: "Eritrea",
  эритрея: "Eritrea",
  estonia: "Estonia",
  эстония: "Estonia",
  eswatini: "Eswatini",
  эсватини: "Eswatini",
  ethiopia: "Ethiopia",
  эфиопия: "Ethiopia",
  fiji: "Fiji",
  фиджи: "Fiji",
  finland: "Finland",
  финляндия: "Finland",
  france: "France",
  франция: "France",
  gabon: "Gabon",
  габон: "Gabon",
  "the gambia": "The Gambia",
  гамбия: "The Gambia",
  georgia: "Georgia",
  грузия: "Georgia",
  germany: "Germany",
  германия: "Germany",
  ghana: "Ghana",
  гана: "Ghana",
  greece: "Greece",
  греция: "Greece",
  grenada: "Grenada",
  гренада: "Grenada",
  guatemala: "Guatemala",
  гватемала: "Guatemala",
  guinea: "Guinea",
  гвинея: "Guinea",
  "guinea-bissau": "Guinea-Bissau",
  "гвинея-бисау": "Guinea-Bissau",
  guyana: "Guyana",
  гайана: "Guyana",
  haiti: "Haiti",
  гаити: "Haiti",
  honduras: "Honduras",
  гондурас: "Honduras",
  hungary: "Hungary",
  венгрия: "Hungary",
  iceland: "Iceland",
  исландия: "Iceland",
  india: "India",
  индия: "India",
  indonesia: "Indonesia",
  индонезия: "Indonesia",
  iran: "Iran",
  иран: "Iran",
  iraq: "Iraq",
  ирак: "Iraq",
  croatia: "Croatia",
  хорватия: "Croatia",
  "south africa": "South Africa",
  юар: "South Africa",
  "dominican republic": "Dominican Republic",
  "доминиканская республика": "Dominican Republic",
  bangladesh: "Bangladesh",
  бангладеш: "Bangladesh",
  monaco: "Monaco",
  монако: "Monaco",
  bashkortostan: "Bashkortostan",
  buryatia: "Buryatia",
  бурятия: "Buryatia",
  chechnya: "Chechnya",
  chuvashia: "Chuvashia",
  чувашия: "Chuvashia",
  dagestan: "Dagestan",
  дагестан: "Dagestan",
  ingushetia: "Ingushetia",
  ингушетия: "Ingushetia",
  "kabardino-balkaria": "Kabardino-Balkaria",
  "кабардино-балкария": "Kabardino-Balkaria",
  kalmykia: "Kalmykia",
  калмыкия: "Kalmykia",
  "karachay-cherkessia": "Karachay-Cherkessia",
  "карачаево- черкессия": "Karachay-Cherkessia",
  karelia: "Karelia",
  карелия: "Karelia",
  khakassia: "Khakassia",
  хакассия: "Khakassia",
  "komi republic": "Komi Republic",
  "республика коми": "Komi Republic",
  "mari el": "Mari El",
  "мари- эл": "Mari El",
  mordovia: "Mordovia",
  мордовия: "Mordovia",
  "north ossetia–alania": "North Ossetia–Alania",
  "северная осетия – алания": "North Ossetia–Alania",
  sakha: "Sakha",
  саха: "Sakha",
  tatarstan: "Tatarstan",
  татарстан: "Tatarstan",
  tuva: "Tuva",
  тува: "Tuva",
  udmurtia: "Udmurtia",
  удмуртия: "Udmurtia",
  "altai krai": "Altai Krai",
  "алтайский край": "Altai Krai",
  "kamchatka krai": "Kamchatka Krai",
  "камчатский край": "Kamchatka Krai",
  "khabarovsk krai": "Khabarovsk Krai",
  "krasnodar krai": "Krasnodar Krai",
  "краснодарский край": "Krasnodar Krai",
  "krasnoyarsk krai": "Krasnoyarsk Krai",
  "красноярский край": "Krasnoyarsk Krai",
  "perm krai": "Perm Krai",
  "пермский край": "Perm Krai",
  "primorsky krai": "Primorsky Krai",
  "приморский край": "Primorsky Krai",
  "stavropol krai": "Stavropol Krai",
  "ставропольский край": "Stavropol Krai",
  "zabaykalsky krai": "Zabaykalsky Krai",
  "забайкальский край": "Zabaykalsky Krai",
  "amur oblast": "Amur Oblast",
  "амурская область": "Amur Oblast",
  "arkhangelsk oblast": "Arkhangelsk Oblast",
  "архангельская область": "Arkhangelsk Oblast",
  "astrakhan oblast": "Astrakhan Oblast",
  "астраханская область": "Astrakhan Oblast",
  "belgorod oblast": "Belgorod Oblast",
  "белгородская область": "Belgorod Oblast",
  alabama: "Alabama",
  алабама: "Alabama",
  alaska: "Alaska",
  аляска: "Alaska",
  arizona: "Arizona",
  аризона: "Arizona",
  arkansas: "Arkansas",
  арканзас: "Arkansas",
  california: "California",
  калифорния: "California",
  colorado: "Colorado",
  колорадо: "Colorado",
  connecticut: "Connecticut",
  коннектикут: "Connecticut",
  delaware: "Delaware",
  делавэр: "Delaware",
  florida: "Florida",
  флорида: "Florida",
  hawaii: "Hawaii",
  гавайи: "Hawaii",
  idaho: "Idaho",
  айдахо: "Idaho",
  illinois: "Illinois",
  ииллинойс: "Illinois",
  indiana: "Indiana",
  индиана: "Indiana",
  iowa: "Iowa",
  айова: "Iowa",
  kansas: "Kansas",
  канзас: "Kansas",
  kentucky: "Kentucky",
  кентукки: "Kentucky",
  louisiana: "Louisiana",
  луизиана: "Louisiana",
  maine: "Maine",
  мэн: "Maine",
  maryland: "Maryland",
  мэриленд: "Maryland",
  massachusetts: "Massachusetts",
  массачусетс: "Massachusetts",
  michigan: "Michigan",
  мичиган: "Michigan",
  minnesota: "Minnesota",
  миннесота: "Minnesota",
  mississippi: "Mississippi",
  миссисипи: "Mississippi",
  missouri: "Missouri",
  миссури: "Missouri",
  montana: "Montana",
  монтана: "Montana",
  nebraska: "Nebraska",
  небраска: "Nebraska",
  nevada: "Nevada",
  невада: "Nevada",
  "new hampshire": "New Hampshire",
  "нью-гэмпшир": "New Hampshire",
  "new jersey": "New Jersey",
  "нью-джерси": "New Jersey",
  "new mexico": "New Mexico",
  "нью-мексико": "New Mexico",
  "new york": "New York",
  "нью-йорк": "New York",
  "north carolina": "North Carolina",
  "северная каролина": "North Carolina",
  "north dakota": "North Dakota",
  "северная дакота": "North Dakota",
  ohio: "Ohio",
  огайо: "Ohio",
  oklahoma: "Oklahoma",
  оклахома: "Oklahoma",
  oregon: "Oregon",
  орегон: "Oregon",
  pennsylvania: "Pennsylvania",
  пенсильвания: "Pennsylvania",
  "rhode island": "Rhode Island",
  "род-айленд": "Rhode Island",
  "south carolina": "South Carolina",
  "южная каролина": "South Carolina",
  "south dakota": "South Dakota",
  "южная дакота": "South Dakota",
  tennessee: "Tennessee",
  теннесси: "Tennessee",
  texas: "Texas",
  техас: "Texas",
  utah: "Utah",
  юта: "Utah",
  vermont: "Vermont",
  вермонт: "Vermont",
  virginia: "Virginia",
  виргиния: "Virginia",
  washington: "Washington",
  вашингтон: "Washington",
  "west virginia": "West Virginia",
  "западная виргиния": "West Virginia",
  wisconsin: "Wisconsin",
  висконсин: "Wisconsin",
  wyoming: "Wyoming",
  вайоминг: "Wyoming",
  "bryansk oblast": "Bryansk Oblast",
  "брянская область": "Bryansk Oblast",
  "chelyabinsk oblast": "Chelyabinsk Oblast",
  "челябинская область": "Chelyabinsk Oblast",
  "irkutsk oblast": "Irkutsk Oblast",
  иркутск: "Irkutsk Oblast",
  "ivanovo oblast": "Ivanovo Oblast",
  "ивановская область": "Ivanovo Oblast",
  "kaliningrad oblast": "Kaliningrad Oblast",
  "калининградская область": "Kaliningrad Oblast",
  "kaluga oblast": "Kaluga Oblast",
  "калужская область": "Kaluga Oblast",
  "kemerovo oblast": "Kemerovo Oblast",
  "кемеровская область": "Kemerovo Oblast",
  "kirov oblast": "Kirov Oblast",
  "кировская область": "Kirov Oblast",
  "kostroma oblast": "Kostroma Oblast",
  "костромская область": "Kostroma Oblast",
  "kurgan oblast": "Kurgan Oblast",
  "курганская область": "Kurgan Oblast",
  "kursk oblast": "Kursk Oblast",
  "курская область": "Kursk Oblast",
  "leningrad oblast": "Leningrad Oblast",
  "ленинградская область": "Leningrad Oblast",
  "нижегородская область": "Nizhny Novgorod Oblast",
  "lipetsk oblast": "Lipetsk Oblast",
  "липецкая область": "Lipetsk Oblast",
  "magadan oblast": "Magadan Oblast",
  "магаданская область": "Magadan Oblast",
  "moscow oblast": "Moscow Oblast",
  "московская область": "Moscow Oblast",
  "murmansk oblast": "Murmansk Oblast",
  "мурманская область": "Murmansk Oblast",
  "nizhny novgorod oblast": "Nizhny Novgorod Oblast",
  "novgorod oblast": "Novgorod Oblast",
  "новгородская область": "Novgorod Oblast",
  "novosibirsk oblast": "Novosibirsk Oblast",
  "новосибирская область": "Novosibirsk Oblast",
  "omsk oblast": "Omsk Oblast",
  "омская область": "Omsk Oblast",
  "orenburg oblast": "Orenburg Oblast",
  "оренбургская область": "Orenburg Oblast",
  "oryol oblast": "Oryol Oblast",
  "орловская область": "Oryol Oblast",
  "penza oblast": "Penza Oblast",
  "пензенская область": "Penza Oblast",
  "pskov oblast": "Pskov Oblast",
  "псковская область": "Pskov Oblast",
  "rostov oblast": "Rostov Oblast",
  "ростовская область, ": "Rostov Oblast",
  "ryazan oblast": "Ryazan Oblast",
  "рязанская область": "Ryazan Oblast",
  "sakhalin oblast": "Sakhalin Oblast",
  "сахалинская область": "Sakhalin Oblast",
  "samara oblast": "Samara Oblast",
  "самарская область": "Samara Oblast",
  "saratov oblast": "Saratov Oblast",
  "саратовская область": "Saratov Oblast",
  "smolensk oblast": "Smolensk Oblast",
  "смоленская область": "Smolensk Oblast",
  "sverdlovsk oblast": "Sverdlovsk Oblast",
  "свердловская область": "Sverdlovsk Oblast",
  "tambov oblast": "Tambov Oblast",
  "тамбовская область": "Tambov Oblast",
  "tomsk oblast": "Tomsk Oblast",
  "томская область": "Tomsk Oblast",
  "tula oblast": "Tula Oblast",
  "тульская область": "Tula Oblast",
  "tver oblast": "Tver Oblast",
  "тверская область": "Tver Oblast",
  "tyumen oblast": "Tyumen Oblast",
  "тюменская область": "Tyumen Oblast",
  "ulyanovsk oblast": "Ulyanovsk Oblast",
  "ульяновская область": "Ulyanovsk Oblast",
  "vladimir oblast": "Vladimir Oblast",
  "владимирская область": "Vladimir Oblast",
  "volgograd oblast": "Volgograd Oblast",
  "волгоградская область": "Volgograd Oblast",
  "vologda oblast": "Vologda Oblast",
  "вологодская область": "Vologda Oblast",
  "voronezh oblast": "Voronezh Oblast",
  "воронежская область": "Voronezh Oblast",
  "yaroslavl oblast": "Yaroslavl Oblast",
  "ярославская область": "Yaroslavl Oblast",
  "jewish autonomous oblast": "Jewish Autonomous Oblast",
  "еврейская автономная область": "Jewish Autonomous Oblast",
  "chukotka autonomous okrug": "Chukotka Autonomous Okrug",
  "чукотский автономный округ": "Chukotka Autonomous Okrug",
  "khanty–mansi autonomous okrug": "Khanty–Mansi Autonomous Okrug",
  "ханты-мансийский автономный округ": "Khanty–Mansi Autonomous Okrug",
  "nenetsautonomous okrug": "NenetsAutonomous Okrug",
  "ненецкий автономный округ": "NenetsAutonomous Okrug",
  "yamalo-nenets autonomous okrug": "Yamalo-Nenets Autonomous Okrug",
  "ямало-ненецкий автономный округ": "Yamalo-Nenets Autonomous Okrug",
  moscow: "Moscow",
  москва: "Moscow",
  "saint petersburg": "Saint Petersburg",
  "санкт-петербург": "Saint Petersburg",
  "cherkasy oblast": "Cherkasy Oblast",
  "черкасская область": "Cherkasy Oblast",
  "chernivtsi oblast": "Chernivtsi Oblast",
  "черновицкая область": "Chernivtsi Oblast",
  "chernihiv oblast": "Chernihiv Oblast",
  "черниговская область": "Chernihiv Oblast",
  "dnipropetrovsk oblast": "Dnipropetrovsk Oblast",
  "днепропетровская область": "Dnipropetrovsk Oblast",
  "donetsk oblast": "Donetsk Oblast",
  "донецкая область": "Donetsk Oblast",
  "ivano-frankivsk oblast": "Ivano-Frankivsk Oblast",
  "ивано-франковская область": "Ivano-Frankivsk Oblast",
  "kharkiv oblast": "Kharkiv Oblast",
  "харьковская область": "Kharkiv Oblast",
  "kherson oblast": "Kherson Oblast",
  "херсонская область": "Kherson Oblast",
  "khmelnytskyi oblast": "Khmelnytskyi Oblast",
  "хмельницкая область": "Khmelnytskyi Oblast",
  "kirovohrad oblast": "Kirovohrad Oblast",
  "кировоградская область": "Kirovohrad Oblast",
  "kyiv oblast": "Kyiv Oblast",
  "киевская область": "Kyiv Oblast",
  "luhansk oblast": "Luhansk Oblast",
  "луганская область": "Luhansk Oblast",
  "lviv oblast": "Lviv Oblast",
  "львовская область": "Lviv Oblast",
  "mykolaiv oblast": "Mykolaiv Oblast",
  "николаевская область": "Mykolaiv Oblast",
  "odesa oblast": "Odesa Oblast",
  "одесская область": "Odesa Oblast",
  "poltava oblast": "Poltava Oblast",
  "полтавская область": "Poltava Oblast",
  "rivne oblast": "Rivne Oblast",
  "ровенская область": "Rivne Oblast",
  "sumy oblast": "Sumy Oblast",
  "сумская область": "Sumy Oblast",
  "ternopil oblast": "Ternopil Oblast",
  "тернопольская область": "Ternopil Oblast",
  "vinnytsia oblast": "Vinnytsia Oblast",
  "винницкая область": "Vinnytsia Oblast",
  "volyn oblast": "Volyn Oblast",
  "волынская область": "Volyn Oblast",
  "zaporizhia oblast": "Zaporizhia Oblast",
  "запорожская область": "Zaporizhia Oblast",
  "zakarpattia oblast": "Zakarpattia Oblast",
  "закарпатская область": "Zakarpattia Oblast",
  "zhytomyr oblast": "Zhytomyr Oblast",
  "житомирская область": "Zhytomyr Oblast",
  crimea: "Crimea",
  крым: "Crimea",
  kyiv: "Kyiv",
  киев: "Kyiv",
  sevastopol: "Sevastopol",
  севастополь: "Sevastopol",
  israel: "Israel",
  израиль: "Israel",
  kuwait: "Kuwait",
  кувейт: "Kuwait",
  "minsk city": "Minsk City",
  минск: "Minsk City",
  "brest region": "Brest Region",
  "брестская область": "Brest Region",
  "gomel region": "Gomel Region",
  "гомельская область": "Gomel Region",
  "grodno region": "Grodno Region",
  "гродненская область": "Grodno Region",
  ireland: "Ireland",
  ирландия: "Ireland",
  italy: "Italy",
  италия: "Italy",
  "ivory coast": "Ivory Coast",
  "кот-д'ивуар": "Ivory Coast",
  jamaica: "Jamaica",
  ямайка: "Jamaica",
  japan: "Japan",
  япония: "Japan",
  jordan: "Jordan",
  иордания: "Jordan",
  kazakhstan: "Kazakhstan",
  казахстан: "Kazakhstan",
  kenya: "Kenya",
  кения: "Kenya",
  kiribati: "Kiribati",
  кирибати: "Kiribati",
  kyrgyzstan: "Kyrgyzstan",
  кыргызстан: "Kyrgyzstan",
  laos: "Laos",
  лаос: "Laos",
  latvia: "Latvia",
  латвия: "Latvia",
  lebanon: "Lebanon",
  ливан: "Lebanon",
  lesotho: "Lesotho",
  лесото: "Lesotho",
  liberia: "Liberia",
  либерия: "Liberia",
  libya: "Libya",
  ливия: "Libya",
  liechtenstein: "Liechtenstein",
  лихтенштейн: "Liechtenstein",
  lithuania: "Lithuania",
  литва: "Lithuania",
  luxembourg: "Luxembourg",
  люксембург: "Luxembourg",
  madagascar: "Madagascar",
  мадагаскар: "Madagascar",
  malawi: "Malawi",
  малави: "Malawi",
  malaysia: "Malaysia",
  малайзия: "Malaysia",
  maldives: "Maldives",
  мальдивы: "Maldives",
  mali: "Mali",
  мали: "Mali",
  malta: "Malta",
  мальта: "Malta",
  "marshall islands": "Marshall Islands",
  "маршалловы острова": "Marshall Islands",
  mauritania: "Mauritania",
  мавритания: "Mauritania",
  mauritius: "Mauritius",
  маврикий: "Mauritius",
  mexico: "Mexico",
  мексика: "Mexico",
  micronesia: "Micronesia",
  микронезия: "Micronesia",
  moldova: "Moldova",
  молдова: "Moldova",
  "mogilev region": "Mogilev Region",
  "могилевская область": "Mogilev Region",
  "minsk region": "Minsk Region",
  "минская область": "Minsk Region",
  "vitebsk region": "Vitebsk Region",
  "витебская область": "Vitebsk Region",
  mongolia: "Mongolia",
  монголия: "Mongolia",
  montenegro: "Montenegro",
  черногория: "Montenegro",
  morocco: "Morocco",
  марокко: "Morocco",
  mozambique: "Mozambique",
  мозамбик: "Mozambique",
  myanmar: "Myanmar",
  мьянма: "Myanmar",
  namibia: "Namibia",
  намибия: "Namibia",
  nauru: "Nauru",
  науру: "Nauru",
  nepal: "Nepal",
  непал: "Nepal",
  netherlands: "Netherlands",
  нидерланды: "Netherlands",
  "new zealand": "New Zealand",
  "новая зеландия": "New Zealand",
  nicaragua: "Nicaragua",
  никарагуа: "Nicaragua",
  niger: "Niger",
  нигер: "Niger",
  nigeria: "Nigeria",
  нигерия: "Nigeria",
  "north korea": "North Korea",
  "северная корея": "North Korea",
  "north macedonia": "North Macedonia",
  "северная македония": "North Macedonia",
  norway: "Norway",
  норвегия: "Norway",
  oman: "Oman",
  оман: "Oman",
  pakistan: "Pakistan",
  пакистан: "Pakistan",
  palau: "Palau",
  палау: "Palau",
  palestine: "Palestine",
  палестина: "Palestine",
  panama: "Panama",
  панама: "Panama",
  "papua new guinea": "Papua New Guinea",
  "папуа-новая гвинея": "Papua New Guinea",
  paraguay: "Paraguay",
  парагвай: "Paraguay",
  peru: "Peru",
  перу: "Peru",
  philippines: "Philippines",
  филиппины: "Philippines",
  poland: "Poland",
  польша: "Poland",
  portugal: "Portugal",
  португалия: "Portugal",
  qatar: "Qatar",
  катар: "Qatar",
  romania: "Romania",
  румыния: "Romania",
  russia: "Russia",
  россия: "Russia",
  rwanda: "Rwanda",
  руанда: "Rwanda",
  "saint kitts and nevis": "Saint Kitts and Nevis",
  "сент-китс и невис": "Saint Kitts and Nevis",
  "saint lucia": "Saint Lucia",
  "сент-люсия": "Saint Lucia",
  "saint vincent and the grenadines": "Saint Vincent and the Grenadines",
  "сент-винсент и гренадины": "Saint Vincent and the Grenadines",
  samoa: "Samoa",
  самоа: "Samoa",
  "san marino": "San Marino",
  "сан-марино": "San Marino",
  "são tomé and príncipe": "São Tomé and Príncipe",
  "сан-томе и принсипи": "São Tomé and Príncipe",
  "saudi arabia": "Saudi Arabia",
  "саудовская аравия": "Saudi Arabia",
  senegal: "Senegal",
  сенегал: "Senegal",
  serbia: "Serbia",
  сербия: "Serbia",
  seychelles: "Seychelles",
  "сейшельские о-ва": "Seychelles",
  "sierra leone": "Sierra Leone",
  "сьерра-леоне": "Sierra Leone",
  singapore: "Singapore",
  сингапур: "Singapore",
  slovakia: "Slovakia",
  словакия: "Slovakia",
  slovenia: "Slovenia",
  словения: "Slovenia",
  "solomon islands": "Solomon Islands",
  "соломоновы о-ва": "Solomon Islands",
  somalia: "Somalia",
  сомали: "Somalia",
  "south korea": "South Korea",
  "южная корея": "South Korea",
  "south sudan": "South Sudan",
  "южный судан": "South Sudan",
  spain: "Spain",
  испания: "Spain",
  "sri lanka": "Sri Lanka",
  "шри-ланка": "Sri Lanka",
  sudan: "Sudan",
  судан: "Sudan",
  suriname: "Suriname",
  суринам: "Suriname",
  sweden: "Sweden",
  швеция: "Sweden",
  switzerland: "Switzerland",
  швейцария: "Switzerland",
  syria: "Syria",
  сирия: "Syria",
  tajikistan: "Tajikistan",
  таджикистан: "Tajikistan",
  tanzania: "Tanzania",
  танзания: "Tanzania",
  thailand: "Thailand",
  таиланд: "Thailand",
  "timor-leste": "Timor-Leste",
  "восточный тимор": "Timor-Leste",
  togo: "Togo",
  того: "Togo",
  tonga: "Tonga",
  тонга: "Tonga",
  "trinidad and tobago": "Trinidad and Tobago",
  "тринидад и тобаго": "Trinidad and Tobago",
  tunisia: "Tunisia",
  тунис: "Tunisia",
  turkey: "Turkey",
  турция: "Turkey",
  turkmenistan: "Turkmenistan",
  туркменистан: "Turkmenistan",
  tuvalu: "Tuvalu",
  тувалу: "Tuvalu",
  uganda: "Uganda",
  уганда: "Uganda",
  ukraine: "Ukraine",
  украина: "Ukraine",
  "united arab emirates": "United Arab Emirates",
  "объединенные арабские эмираты": "United Arab Emirates",
  "united kingdom": "United Kingdom",
  великобритания: "United Kingdom",
  uk: "United Kingdom",
  "united states": "United States",
  "соединенные штаты америки": "United States",
  usa: "United States",
  us: "United States",
  сша: "United States",
  "соединенные штаты": "United States",
  uruguay: "Uruguay",
  уругвай: "Uruguay",
  uzbekistan: "Uzbekistan",
  узбекистан: "Uzbekistan",
  vanuatu: "Vanuatu",
  вануату: "Vanuatu",
  "vatican city": "Vatican City",
  ватикан: "Vatican City",
  venezuela: "Venezuela",
  венесуэла: "Venezuela",
  vietnam: "Vietnam",
  вьетнам: "Vietnam",
  yemen: "Yemen",
  йемен: "Yemen",
  zambia: "Zambia",
  замбия: "Zambia",
  abkhazia: "Abkhazia",
  абхазия: "Abkhazia",
  kosovo: "Kosovo",
  косово: "Kosovo",
  "northern cyprus": "Northern Cyprus",
  "северный кипр": "Northern Cyprus",
  "sahrawi arab democratic republic": "Sahrawi Arab Democratic Republic",
  "сахарская арабская демократическая республика":
    "Sahrawi Arab Democratic Republic",
  "сахарская республика": "Sahrawi Arab Democratic Republic",
  сахара: "Sahrawi Arab Democratic Republic",
  "сахарская АДР": "Sahrawi Arab Democratic Republic",
  "south ossetia": "South Ossetia",
  "южная осетия": "South Ossetia",
  taiwan: "Taiwan",
  тайвань: "Taiwan",
  transnistria: "Transnistria",
  "приднестровская молдавская республика": "Transnistria",
  приднестровье: "Transnistria",
  somaliland: "Somaliland",
  сомалиленд: "Somaliland",
  zimbabwe: "Zimbabwe",
  зимбабве: "Zimbabwe",
  bryansk: "Bryansk Oblast",
  брянская: "Bryansk Oblast",
  chelyabinsk: "Chelyabinsk Oblast",
  челябинская: "Chelyabinsk Oblast",
  irkutsk: "Irkutsk Oblast",
  ivanovo: "Ivanovo Oblast",
  ивановская: "Ivanovo Oblast",
  kaliningrad: "Kaliningrad Oblast",
  калининградская: "Kaliningrad Oblast",
  kaluga: "Kaluga Oblast",
  калуга: "Kaluga Oblast",
  kemerovo: "Kemerovo Oblast",
  кемеров: "Kemerovo Oblast",
  kirov: "Kirov Oblast",
  киров: "Kirov Oblast",
  kostroma: "Kostroma Oblast",
  костромская: "Kostroma Oblast",
  kurgan: "Kurgan Oblast",
  курганская: "Kurgan Oblast",
  kursk: "Kursk Oblast",
  курская: "Kursk Oblast",
  leningrad: "Leningrad Oblast",
  ленинградская: "Leningrad Oblast",
  нижегородская: "Nizhny Novgorod Oblast",
  lipetsk: "Lipetsk Oblast",
  липецкая: "Lipetsk Oblast",
  magadan: "Magadan Oblast",
  магаданская: "Magadan Oblast",
  московская: "Moscow Oblast",
  murmansk: "Murmansk Oblast",
  мурманская: "Murmansk Oblast",
  "nizhny novgorod": "Nizhny Novgorod Oblast",
  novgorod: "Novgorod Oblast",
  новгородская: "Novgorod Oblast",
  novosibirsk: "Novosibirsk Oblast",
  новосибирская: "Novosibirsk Oblast",
  omsk: "Omsk Oblast",
  омская: "Omsk Oblast",
  orenburg: "Orenburg Oblast",
  оренбургская: "Orenburg Oblast",
  oryol: "Oryol Oblast",
  орловская: "Oryol Oblast",
  penza: "Penza Oblast",
  пензенская: "Penza Oblast",
  pskov: "Pskov Oblast",
  псковская: "Pskov Oblast",
  rostov: "Rostov Oblast",
  "ростовская, ": "Rostov Oblast",
  ryazan: "Ryazan Oblast",
  рязанская: "Ryazan Oblast",
  sakhalin: "Sakhalin Oblast",
  сахалинская: "Sakhalin Oblast",
  samara: "Samara Oblast",
  самарская: "Samara Oblast",
  saratov: "Saratov Oblast",
  саратовская: "Saratov Oblast",
  smolensk: "Smolensk Oblast",
  смоленская: "Smolensk Oblast",
  sverdlovsk: "Sverdlovsk Oblast",
  свердловская: "Sverdlovsk Oblast",
  tambov: "Tambov Oblast",
  тамбовская: "Tambov Oblast",
  tomsk: "Tomsk Oblast",
  томская: "Tomsk Oblast",
  tula: "Tula Oblast",
  тульская: "Tula Oblast",
  tver: "Tver Oblast",
  тверская: "Tver Oblast",
  tyumen: "Tyumen Oblast",
  тюменская: "Tyumen Oblast",
  ulyanovsk: "Ulyanovsk Oblast",
  ульяновская: "Ulyanovsk Oblast",
  vladimir: "Vladimir Oblast",
  владимирская: "Vladimir Oblast",
  volgograd: "Volgograd Oblast",
  волгоградская: "Volgograd Oblast",
  vologda: "Vologda Oblast",
  вологодская: "Vologda Oblast",
  voronezh: "Voronezh Oblast",
  воронежская: "Voronezh Oblast",
  yaroslavl: "Yaroslavl Oblast",
  ярославль: "Yaroslavl Oblast",
  jewish: "Jewish Autonomous Oblast",
  еврейская: "Jewish Autonomous Oblast",
  chukotka: "Chukotka Autonomous Okrug",
  чукотский: "Chukotka Autonomous Okrug",
  "khanty–mansi": "Khanty–Mansi Autonomous Okrug",
  "ханты-мансийский": "Khanty–Mansi Autonomous Okrug",
  "nenets autonomous okrug": "Nenets Autonomous Okrug",
  ненецкий: "NenetsAutonomous Okrug",
  "yamalo-nenets": "Yamalo-Nenets Autonomous Okrug",
  "ямало-ненецкий": "Yamalo-Nenets Autonomous Okrug",
  cherkasy: "Cherkasy Oblast",
  черкасская: "Cherkasy Oblast",
  chernivtsi: "Chernivtsi Oblast",
  черновицкая: "Chernivtsi Oblast",
  chernihiv: "Chernihiv Oblast",
  черниговская: "Chernihiv Oblast",
  dnipropetrovsk: "Dnipropetrovsk Oblast",
  днепропетровская: "Dnipropetrovsk Oblast",
  donetsk: "Donetsk Oblast",
  донецкая: "Donetsk Oblast",
  "ivano-frankivsk": "Ivano-Frankivsk Oblast",
  "ивано-франковская": "Ivano-Frankivsk Oblast",
  kharkiv: "Kharkiv Oblast",
  харьковская: "Kharkiv Oblast",
  kherson: "Kherson Oblast",
  херсонская: "Kherson Oblast",
  khmelnytskyi: "Khmelnytskyi Oblast",
  хмельницкая: "Khmelnytskyi Oblast",
  kirovohrad: "Kirovohrad Oblast",
  кировоградская: "Kirovohrad Oblast",
  киевская: "Kyiv Oblast",
  luhansk: "Luhansk Oblast",
  луганская: "Luhansk Oblast",
  lviv: "Lviv Oblast",
  львовская: "Lviv Oblast",
  mykolaiv: "Mykolaiv Oblast",
  николаевская: "Mykolaiv Oblast",
  odesa: "Odesa Oblast",
  одесская: "Odesa Oblast",
  poltava: "Poltava Oblast",
  полтавская: "Poltava Oblast",
  rivne: "Rivne Oblast",
  ровенская: "Rivne Oblast",
  sumy: "Sumy Oblast",
  сумская: "Sumy Oblast",
  ternopil: "Ternopil Oblast",
  тернопольская: "Ternopil Oblast",
  vinnytsia: "Vinnytsia Oblast",
  винницкая: "Vinnytsia Oblast",
  volyn: "Volyn Oblast",
  волынская: "Volyn Oblast",
  zaporizhia: "Zaporizhia Oblast",
  запорожская: "Zaporizhia Oblast",
  zakarpattia: "Zakarpattia Oblast",
  закарпатская: "Zakarpattia Oblast",
  zhytomyr: "Zhytomyr Oblast",
  житомирская: "Zhytomyr Oblast",
};
